version: '3'
services:
  todotests:
    image: todotests
    environment: 
      - FRONT_HOST=front
    depends_on:
      - todofront
      - todoback
  todofront:
    image: todofrontend
    depends_on:
      - todoback
    ports:
      - 3000:3000
    container_name: front
    environment: 
      - REACT_APP_API_HOST=back
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    container_name: back
